# Generated by Django 5.0.6 on 2024-06-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBBs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
